"""
Curriculum types — data models for the Dynamic Curriculum Engine.

Knowledge Graph nodes, learning path steps, and path planning results.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class KnowledgeNode(BaseModel):
    """A single topic/skill node in the knowledge graph.

    Represents a teachable unit with prerequisites, difficulty, and
    associated learning resources.
    """

    topic_id: str = Field(..., description="Unique topic identifier, e.g. 'python_basics'")
    name: str = Field(..., description="Human-readable topic name")
    subject: str = Field(..., description="Parent subject, e.g. 'python', 'math'")
    difficulty: float = Field(default=0.5, ge=0.0, le=1.0, description="Topic difficulty 0→1")
    estimated_hours: float = Field(default=10.0, ge=0.0, description="Estimated study hours")
    prerequisites: list[str] = Field(default_factory=list, description="topic_ids that must be learned first")
    knowledge_points: list[str] = Field(default_factory=list, description="Specific KPs covered")
    resources: dict[str, list[str]] = Field(
        default_factory=dict,
        description="resource_type → list of resource names, e.g. {'quiz': ['list comp practice']}",
    )
    metadata: dict[str, Any] = Field(default_factory=dict, description="Extensible metadata")


class PathStep(BaseModel):
    """One step in a personalized learning path.

    Each step maps a knowledge graph topic to the user's current state,
    with a computed status and recommended resources.
    """

    topic_id: str
    name: str
    subject: str
    status: Literal["skip", "ready", "blocked", "reinforce", "repeat"] = Field(
        default="blocked",
        description="skip=mastered, ready=can start, blocked=missing prereqs, reinforce=weak, repeat=recently failed",
    )
    user_skill_level: float = Field(default=0.0, ge=0.0, le=1.0, description="User's current skill level")
    skill_confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Confidence in skill estimate")
    topic_difficulty: float = Field(default=0.5, ge=0.0, le=1.0)
    estimated_hours: float = Field(default=10.0, ge=0.0)
    recommended_resources: list[dict] = Field(
        default_factory=list,
        description="[{'type': 'quiz', 'name': '...', 'reason': '...'}]",
    )
    priority: float = Field(default=0.5, ge=0.0, le=1.0, description="Computed priority for ordering")
    status_reason: str = Field(default="", description="Why this status was assigned")
    missing_prerequisites: list[str] = Field(default_factory=list, description="Prereqs not yet met")


class LearningPath(BaseModel):
    """A personalized, KG-aware learning path for a user.

    Generated by the path planner based on user profile skills,
    semantic memory weak points, and knowledge graph structure.
    """

    user_id: str
    generated_at: str
    goal_subject: str = ""
    goal_topics: list[str] = Field(default_factory=list)
    steps: list[PathStep] = Field(default_factory=list)
    estimated_total_hours: float = Field(default=0.0, ge=0.0)
    summary: str = Field(default="", description="Natural language summary of the path")
    skip_count: int = 0
    reinforce_count: int = 0
    repeat_count: int = 0
    ready_count: int = 0
    blocked_count: int = 0

    @property
    def active_steps(self) -> list[PathStep]:
        """Return steps that are NOT skipped (ready, reinforce, repeat, blocked)."""
        return [s for s in self.steps if s.status != "skip"]

    @property
    def actionable_steps(self) -> list[PathStep]:
        """Return steps that can be started now (ready, reinforce, repeat)."""
        return [s for s in self.steps if s.status in ("ready", "reinforce", "repeat")]


class PathPlannerInput(BaseModel):
    """Input to the path planner — collected from profile + memory."""

    user_id: str
    goal_subject: str
    goal_topics: list[str]
    skill_levels: dict[str, float]  # topic_id → level
    skill_confidences: dict[str, float]  # topic_id → confidence
    weak_knowledge_points: list[str]  # from semantic memory
    recent_failures: list[str]  # topic_ids failed in last 7 days
