export const NOW = "2026-07-11T08:00:00+00:00"
export const LATER = "2026-07-11T08:00:01+00:00"

export function activityPayload(overrides: Record<string, unknown> = {}) {
  return {
    schema_version: "activity_event_v1",
    activity_id: "activity:v1:fixture",
    sequence: 1,
    thread_id: "thread-fixture",
    request_id: "request-fixture",
    kind: "node",
    status: "running",
    node: "fixture_node",
    parent: "",
    title: "后端活动标题",
    summary: "安全活动摘要",
    tool: "",
    model: "",
    started_at: NOW,
    updated_at: NOW,
    completed_at: "",
    duration_ms: null,
    safe_details: {},
    ...overrides,
  }
}

export function contextUsageReportPayload(overrides: Record<string, unknown> = {}) {
  return {
    schema_version: "context_usage_report_v1",
    report_id: "context_usage:v1:fixture",
    manifest_id: "llm_input_manifest:v1:fixture",
    created_at: NOW,
    request_id: "request-fixture",
    thread_id: "thread-fixture",
    node_name: "fixture_node",
    llm_node: "fixture_llm_node",
    provider: "configured-provider",
    model: "configured-model",
    input_estimated_tokens: 100,
    output_reserved_tokens: 20,
    used_tokens: 120,
    max_context_tokens: 1000,
    available_tokens: 880,
    used_ratio: 0.12,
    warning_level: "ok",
    estimated: true,
    tokenizer_mode: "estimated",
    message_count: 2,
    schema_size_chars: null,
    main_categories: [
      { category: "system_prompt", estimated_tokens: 60, segment_count: 1, message_count: 1 },
      { category: "conversation", estimated_tokens: 40, segment_count: 1, message_count: 1 },
    ],
    detailed_categories: [
      { category: "business_prompt", estimated_tokens: 60, segment_count: 1, message_count: 1 },
      { category: "recent_messages", estimated_tokens: 40, segment_count: 1, message_count: 1 },
    ],
    overlap_rollups: [],
    segments: [
      {
        segment_id: "segment:v1:system",
        fingerprint: "0123456789abcdef",
        message_index: 0,
        role: "system",
        main_category: "system_prompt",
        detailed_category: "business_prompt",
        char_count: 240,
        estimated_tokens: 60,
        provenance: { source: "messages" },
      },
      {
        segment_id: "segment:v1:user",
        fingerprint: "fedcba9876543210",
        message_index: 1,
        role: "user",
        main_category: "conversation",
        detailed_category: "recent_messages",
        char_count: 160,
        estimated_tokens: 40,
        provenance: { source: "messages" },
      },
    ],
    unclassified_tokens: 0,
    reconciliation_ok: true,
    reconciliation_warnings: [],
    ...overrides,
  }
}

export function backgroundContextPayload(overrides: Record<string, unknown> = {}) {
  return {
    schema_version: 1,
    thread_id: "thread-fixture",
    updated_at: NOW,
    last_manifest_id: "llm_input_manifest:v1:fixture",
    used_tokens: 120,
    max_context_tokens: 1000,
    used_ratio: 0.12,
    message_count: 2,
    section_count: 2,
    section_names: ["business_prompt", "recent_messages"],
    conversation_summary_present: true,
    selected_memory_count: 1,
    artifact_summary_count: 2,
    evidence_summary_count: 3,
    ce_block_present: true,
    structured_contract_present: false,
    manifest_count: 4,
    influence_entry_count: 2,
    influence_token_estimate: 80,
    influence_source_node_count: 1,
    workspace_present: true,
    workspace_active_subject: "machine learning",
    workspace_evidence_summary_count: 3,
    workspace_gap_count: 1,
    workspace_artifact_count: 2,
    workspace_updated_at: NOW,
    ...overrides,
  }
}

export function threadContextWindowV2Payload(overrides: Record<string, unknown> = {}) {
  const section = {
    section: "recent_messages",
    source: "current_thread_state",
    item_count: 2,
    message_count: 2,
    char_count: 400,
    estimated_tokens: 100,
    known: true,
  }
  return {
    schema_version: 2,
    contract: "thread_context_window_v2",
    thread_id: "thread-fixture",
    updated_at: NOW,
    next_call_context_estimate: {
      basis: "thread_baseline",
      confidence: "low",
      estimated: true,
      estimated_at: NOW,
      target_node: "",
      unknown_sections: ["ce_block", "structured_output_contract"],
      sections: [section],
      estimated_input_tokens: 100,
      estimated_output_reserved_tokens: 0,
      estimated_used_tokens: 100,
      max_context_tokens: 1000,
      used_ratio: 0.1,
      tokenizer_mode: "estimated_mixed",
      state_fingerprint: `thread_context:v2:${"a".repeat(64)}`,
      reused_manifest_statistics: false,
      known_section_ratio: 0.3333,
    },
    last_llm_call_usage: {
      present: true,
      report_id: "context_usage:v1:fixture",
      manifest_id: "llm_input_manifest:v1:fixture",
      created_at: NOW,
      node_name: "fixture_node",
      llm_node: "fixture_llm_node",
      model: "configured-model",
      input_estimated_tokens: 100,
      output_reserved_tokens: 20,
      used_tokens: 120,
      max_context_tokens: 1000,
      used_ratio: 0.12,
      estimated: true,
      tokenizer_mode: "estimated_mixed",
      sections: [section],
    },
    background_inventory: {
      conversation_summary_present: true,
      selected_memory_count: 1,
      evidence_summary_count: 3,
      artifact_summary_count: 2,
      workspace_present: true,
      workspace_active_subject: "machine learning",
      workspace_evidence_summary_count: 3,
      workspace_gap_count: 1,
      workspace_artifact_count: 2,
      workspace_updated_at: NOW,
      manifest_count: 4,
      influence_entry_count: 2,
    },
    ...overrides,
  }
}

export function graphManifestPayload(overrides: Record<string, unknown> = {}) {
  return {
    schema_version: "graph_manifest_v1",
    graph_version: "graph:v1:fixture",
    generated_at: NOW,
    nodes: [
      {
        node_id: "start_node",
        label: "后端起点",
        description: "由后端定义",
        kind: "router",
        group: "core",
        parent: "",
        workflow: "",
        order: 1,
        stage_rank: 1,
        visible: true,
        logical: false,
        activity_running: "执行起点",
        activity_completed: "起点完成",
      },
      {
        node_id: "output_node",
        label: "后端输出",
        description: "由后端定义",
        kind: "output",
        group: "core",
        parent: "",
        workflow: "",
        order: 2,
        stage_rank: 2,
        visible: true,
        logical: false,
        activity_running: "生成输出",
        activity_completed: "输出完成",
      },
    ],
    edges: [
      {
        edge_id: "start-output",
        source: "start_node",
        target: "output_node",
        kind: "graph",
        conditional: false,
        label: "",
        workflow: "",
      },
    ],
    capability_metadata: {
      resource_types: [],
      context_policy_mode: "configured",
      checkpointer_enabled: true,
      checkpointer_type: "postgres",
      physical_node_count: 2,
      logical_node_count: 0,
    },
    ...overrides,
  }
}
