"""Strict learner-guidance domain contracts and dependency boundary."""

from src.learning_guidance.contracts import (
    LearnerGoalSignalV1,
    LearnerHistoryEventV1,
    LearnerHistorySnapshotV1,
    LearnerPathEngineRequestV1,
    LearnerPathPlanV1,
    LearnerPathPlannerOutputV1,
    LearnerPathStepV1,
    LearnerPreferenceSignalV1,
    LearnerProfileSnapshotV1,
    LearnerSkillSignalV1,
    RecommendationMode,
    RecommendationResourceContextV1,
    RecommendationScoreFactorsV1,
    RecommendationScoreWeightsV1,
    ResourceRecommendationBatchV1,
    ResourceRecommendationEngineRequestV1,
    ResourceRecommendationEngineResultV1,
    ResourceRecommendationItemV1,
    ResourceRecommendationOutputV1,
)
from src.learning_guidance.runtime import (
    LearningGuidanceContractError,
    LearningGuidanceRuntime,
)
from src.learning_guidance.recommendation_final import (
    ExplicitRecommendationUnavailableReason,
    RecommendationCandidateSnapshotV1,
    RecommendationFinalCandidateV1,
    RecommendationFinalContractError,
    RecommendationFinalItemV1,
    RecommendationFinalV1,
    build_recommendation_final_v1,
    validate_recommendation_final_v1,
)

__all__ = [
    "ExplicitRecommendationUnavailableReason",
    "LearnerGoalSignalV1",
    "LearnerHistoryEventV1",
    "LearnerHistorySnapshotV1",
    "LearnerPathEngineRequestV1",
    "LearnerPathPlanV1",
    "LearnerPathPlannerOutputV1",
    "LearnerPathStepV1",
    "LearnerPreferenceSignalV1",
    "LearnerProfileSnapshotV1",
    "LearnerSkillSignalV1",
    "LearningGuidanceContractError",
    "LearningGuidanceRuntime",
    "RecommendationMode",
    "RecommendationCandidateSnapshotV1",
    "RecommendationFinalCandidateV1",
    "RecommendationFinalContractError",
    "RecommendationFinalItemV1",
    "RecommendationFinalV1",
    "RecommendationResourceContextV1",
    "RecommendationScoreFactorsV1",
    "RecommendationScoreWeightsV1",
    "ResourceRecommendationBatchV1",
    "ResourceRecommendationEngineRequestV1",
    "ResourceRecommendationEngineResultV1",
    "ResourceRecommendationItemV1",
    "ResourceRecommendationOutputV1",
    "build_recommendation_final_v1",
    "validate_recommendation_final_v1",
]
