"""Collaborative mindmap resource-generation nodes."""

from __future__ import annotations

import logging
import os
import re
from typing import Any, Literal

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from src.config import get_setting, load_prompt
from src.graph.llm import async_invoke_with_fallback, get_fallback_llm, get_node_llm
from src.graph.state import TutorState
from src.tools.mindmap_tool import create_xmind_artifact, normalize_mindmap_tree
from src.tracing import traced_llm_call, traced_node

logger = logging.getLogger(__name__)


GENERIC_BRANCH_TITLES = {
    "核心概念",
    "关系层级",
    "易错点",
    "常见误区",
    "实践案例",
    "学习路径",
    "检查点",
    "后续学习路径",
}


class MindmapNode(BaseModel):
    """Unified JSON tree node used by all mindmap renderers."""

    title: str = Field(description="Short concrete node label")
    note: str | None = Field(default=None, description="Optional learning hint")
    children: list["MindmapNode"] = Field(default_factory=list)


class MindmapArtifact(BaseModel):
    """Structured JSON tree generated by mindmap_agent."""

    title: str
    tree: MindmapNode


class MindmapReviewVerdict(BaseModel):
    """Structured quality gate output for mindmap_reviewer."""

    verdict: Literal["approve", "reject"]
    reason: str


if hasattr(MindmapNode, "model_rebuild"):
    MindmapNode.model_rebuild()
else:
    MindmapNode.update_forward_refs()


def _last_human_query(state: TutorState) -> str:
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            return str(msg.content)
    return ""


def _model_to_dict(model: BaseModel) -> dict:
    if hasattr(model, "model_dump"):
        return model.model_dump()
    return model.dict()


def _format_keypoints(state: TutorState) -> str:
    keypoints = state.get("keypoints", [])
    return "、".join(keypoints) if keypoints else "未提取到明确关键词"


def _format_context(context: list[dict]) -> str:
    if not context:
        return (
            "当前课程知识库和外部资料未返回可用依据。可以按高校课程通用知识组织结构生成，"
            "但不得编造教材页码、课程政策或虚假引用来源。"
        )

    parts: list[str] = []
    for idx, item in enumerate(context[:8], 1):
        source = item.get("source") or item.get("title") or item.get("url") or "课程资料"
        content = str(item.get("content") or item.get("snippet") or item.get("text") or "")[:700]
        if not content:
            continue
        parts.append(f"[{idx}] 来源：{source}\n{content}")
    return "\n\n".join(parts) or "已有资料缺少可读正文，请结合用户请求生成通用课程结构。"


def _render_prompt(prompt_name: str, replacements: dict[str, str]) -> str:
    """Render named placeholders without interpreting JSON braces in prompts."""
    prompt = load_prompt(prompt_name)
    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)
    return prompt


def _fallback_outline(query: str, keypoints: list[str], context: list[dict]) -> str:
    items = _extract_concrete_items("\n".join([
        query,
        "、".join(keypoints),
        _format_context(context),
    ]))
    if not items:
        items = keypoints[:12]
    if not items:
        return ""

    selected = _dedupe(items)[:18]
    sections = [
        "1. 核心知识点：" + "、".join(selected[:6]),
        "2. 关系与方法：" + "、".join(selected[6:12] or selected[:4]),
        "3. 易错点与辨析：" + "、".join(selected[12:15] or selected[:3]),
        "4. 实践案例与学习检查：" + "、".join(selected[15:18] or selected[:3]),
    ]
    return "\n".join(sections)


def _extract_concrete_items(text: str) -> list[str]:
    candidates: list[str] = []
    for line in text.splitlines():
        cleaned = re.sub(r"^[\s\-*#>\d.、（）()]+", "", line).strip()
        cleaned = re.sub(r"[:：].*$", "", cleaned).strip()
        if 2 <= len(cleaned) <= 32 and not _is_generic_title(cleaned):
            candidates.append(cleaned)

    for token in re.split(r"[，,、；;。\n\s]+", text):
        cleaned = token.strip("：:（）()[]【】《》\"'")
        if 2 <= len(cleaned) <= 24 and not _is_generic_title(cleaned):
            if re.search(r"[\u4e00-\u9fffA-Za-z]", cleaned):
                candidates.append(cleaned)
    return _dedupe(candidates)


def _dedupe(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        key = value.lower()
        if key not in seen:
            seen.add(key)
            result.append(value)
    return result


def _fallback_tree_from_outline(query: str, outline: str, keypoints: list[str]) -> dict[str, Any]:
    items = _extract_concrete_items(outline)
    if not items:
        items = _extract_concrete_items("、".join(keypoints))
    if not items:
        raise ValueError("mindmap_outline is empty; cannot build a meaningful fallback tree")

    root_title = _clean_title(query, default="知识点思维导图")
    groups = [
        ("概念基础", items[0:4]),
        ("方法机制", items[4:8] or items[0:4]),
        ("易错辨析", items[8:12] or items[:3]),
        ("实践应用", items[12:16] or items[:3]),
    ]
    return {
        "title": root_title,
        "children": [
            {
                "title": branch,
                "children": [
                    {
                        "title": item,
                        "note": "来自知识结构蓝图的具体学习节点。",
                        "children": [{"title": f"{item}的定义/作用"}, {"title": f"{item}的应用检查"}],
                    }
                    for item in branch_items
                ],
            }
            for branch, branch_items in groups
            if branch_items
        ],
    }


def _clean_title(value: str, *, default: str) -> str:
    value = re.sub(r"^(请|帮我|生成|制作|画一个|给我)", "", value.strip())
    value = re.sub(r"[：:，,。.!！?？]+$", "", value)
    return value[:40] or default


def _tree_stats(tree: dict[str, Any]) -> tuple[int, int]:
    def visit(node: Any, depth: int) -> tuple[int, int]:
        if not isinstance(node, dict):
            return 0, depth - 1
        count = 1
        max_depth = depth
        for child in node.get("children") or []:
            child_count, child_depth = visit(child, depth + 1)
            count += child_count
            max_depth = max(max_depth, child_depth)
        return count, max_depth

    return visit(tree, 1)


def _is_generic_title(title: str) -> bool:
    normalized = re.sub(r"\s+", "", title)
    return normalized in GENERIC_BRANCH_TITLES


def _local_review_failure(tree: dict[str, Any], query: str) -> str:
    node_count, depth = _tree_stats(tree)
    if node_count < 10:
        return f"总节点数只有 {node_count} 个，低于知识点思维导图最低要求。"
    if depth < 3:
        return f"树深度只有 {depth} 层，缺少高校课程知识的层级展开。"

    children = tree.get("children") or []
    if children:
        generic_count = sum(
            1 for child in children if isinstance(child, dict) and _is_generic_title(str(child.get("title", "")))
        )
        concrete_grandchildren = [
            grandchild
            for child in children
            if isinstance(child, dict)
            for grandchild in (child.get("children") or [])
            if isinstance(grandchild, dict) and not _is_generic_title(str(grandchild.get("title", "")))
        ]
        if generic_count >= max(3, len(children) - 1) and len(concrete_grandchildren) < 8:
            return "一级分支仍停留在“核心概念/关系层级/易错点/实践案例”等模板类目，缺少具体知识点。"

    query_terms = [
        token
        for token in re.split(r"[，,、；;。\n\s]+", query)
        if 2 <= len(token) <= 20 and not _is_generic_title(token)
    ]
    tree_text = str(tree)
    if query_terms and not any(term in tree_text for term in query_terms[:8]):
        return "导图内容与用户课程主题匹配度不足。"
    return ""


@traced_node
async def mindmap_planner(state: TutorState) -> dict:
    """Build a concrete knowledge-structure blueprint from retrieved evidence."""
    query = _last_human_query(state)
    keypoints = state.get("keypoints", [])
    context = state.get("context", [])
    prompt = _render_prompt(
        "mindmap_planner",
        {
            "question": query,
            "keypoints": _format_keypoints(state),
            "context": _format_context(context),
        },
    )

    llm = get_node_llm("mindmap")
    fallback = get_fallback_llm(temperature=get_setting("mindmap.temperature", 0.2))
    temperature = get_setting("mindmap.temperature", 0.2)
    model_name = get_setting("mindmap.model", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))

    try:
        with traced_llm_call(model_name=model_name, node_name="mindmap_planner", temperature=temperature) as span:
            result = await async_invoke_with_fallback(
                llm,
                [
                    SystemMessage(content="你是高校课程知识结构规划智能体，负责为个性化资源生成提供具体蓝图。"),
                    HumanMessage(content=prompt),
                ],
                fallback=fallback,
                span=span,
            )
        outline = str(getattr(result, "content", result)).strip()
    except Exception:
        logger.warning("Mindmap planner failed, using evidence-based fallback outline", exc_info=True)
        outline = _fallback_outline(query, keypoints, context)

    if not outline:
        outline = _fallback_outline(query, keypoints, context)

    return {
        "mindmap_outline": outline,
        "mindmap_tree": {},
        "mindmap_artifact": {},
        "mindmap_review_verdict": "",
        "mindmap_review_reason": "",
        "mindmap_revision_notes": "",
        "mindmap_round": 0,
    }


@traced_node
async def mindmap_agent(state: TutorState) -> dict:
    """Convert the planned outline into a unified JSON Tree draft."""
    query = _last_human_query(state)
    keypoints = state.get("keypoints", [])
    outline = state.get("mindmap_outline", "")
    revision_notes = state.get("mindmap_revision_notes", "")
    context = state.get("context", [])
    round_no = int(state.get("mindmap_round", 0) or 0) + 1

    if not outline.strip():
        return {
            "error": "知识结构蓝图为空，无法生成有质量保障的思维导图。",
            "mindmap_round": round_no,
        }

    prompt = _render_prompt(
        "mindmap_agent",
        {
            "question": query,
            "keypoints": _format_keypoints(state),
            "context": _format_context(context),
            "mindmap_outline": outline,
            "revision_notes": revision_notes or "暂无审查修订意见。",
        },
    )

    llm = get_node_llm("mindmap")
    structured_llm = llm.with_structured_output(MindmapArtifact)
    fallback = get_fallback_llm(temperature=get_setting("mindmap.temperature", 0.2))
    structured_fallback = fallback.with_structured_output(MindmapArtifact)
    temperature = get_setting("mindmap.temperature", 0.2)
    model_name = get_setting("mindmap.model", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))

    try:
        with traced_llm_call(model_name=model_name, node_name="mindmap_agent", temperature=temperature) as span:
            result = await async_invoke_with_fallback(
                structured_llm,
                [
                    SystemMessage(content="你是 JSON Tree 生成智能体。只输出结构化结果，不输出 Mermaid 或 Markdown。"),
                    HumanMessage(content=prompt),
                ],
                fallback=structured_fallback,
                span=span,
            )
        title = result.title.strip() or "知识点思维导图"
        raw_tree = _model_to_dict(result.tree)
    except Exception:
        logger.warning("Mindmap structured generation failed, using outline fallback tree", exc_info=True)
        try:
            title = "知识点思维导图"
            raw_tree = _fallback_tree_from_outline(query, outline, keypoints)
        except Exception as exc:
            return {
                "error": str(exc),
                "mindmap_round": round_no,
                "mindmap_tree": {},
            }

    tree = normalize_mindmap_tree(raw_tree)
    if not tree.get("title"):
        tree["title"] = title

    return {
        "mindmap_tree": tree,
        "mindmap_round": round_no,
        "mindmap_review_verdict": "",
        "mindmap_review_reason": "",
    }


@traced_node
async def mindmap_reviewer(state: TutorState) -> dict:
    """Review the JSON Tree for A3-style academic resource quality."""
    query = _last_human_query(state)
    tree = state.get("mindmap_tree") or {}
    outline = state.get("mindmap_outline", "")

    if not tree:
        reason = "未生成有效 JSON Tree。"
        return {
            "mindmap_review_verdict": "reject",
            "mindmap_review_reason": reason,
            "mindmap_revision_notes": reason,
        }

    local_failure = _local_review_failure(tree, query)
    if local_failure:
        return {
            "mindmap_review_verdict": "reject",
            "mindmap_review_reason": local_failure,
            "mindmap_revision_notes": f"请据此重写：{local_failure}",
        }

    prompt = _render_prompt(
        "mindmap_reviewer",
        {
            "question": query,
            "mindmap_outline": outline,
            "mindmap_tree": str(tree),
        },
    )

    llm = get_node_llm("mindmap", temperature=get_setting("mindmap.reviewer_temperature", 0.0))
    structured_llm = llm.with_structured_output(MindmapReviewVerdict, method="json_mode")
    fallback = get_fallback_llm(temperature=get_setting("mindmap.reviewer_temperature", 0.0))
    structured_fallback = fallback.with_structured_output(MindmapReviewVerdict, method="json_mode")
    model_name = get_setting("mindmap.model", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))

    try:
        with traced_llm_call(model_name=model_name, node_name="mindmap_reviewer", temperature=0.0) as span:
            result = await async_invoke_with_fallback(
                structured_llm,
                [
                    SystemMessage(content="你是高校课程资源质量审查智能体，只返回 JSON 审查结论。"),
                    HumanMessage(content=prompt),
                ],
                fallback=structured_fallback,
                span=span,
            )
        verdict = result.verdict
        reason = result.reason.strip()
    except Exception:
        logger.warning("Mindmap reviewer failed, approving tree that passed local checks", exc_info=True)
        verdict = "approve"
        reason = "已通过本地结构质量检查。"

    return {
        "mindmap_review_verdict": verdict,
        "mindmap_review_reason": reason,
        "mindmap_revision_notes": "" if verdict == "approve" else f"请据此重写：{reason}",
    }


@traced_node
async def mindmap_rewrite(state: TutorState) -> dict:
    """Prepare reviewer feedback for the next JSON Tree generation attempt."""
    reason = state.get("mindmap_review_reason", "")
    outline = state.get("mindmap_outline", "")
    notes = (
        f"{reason}\n"
        "重写要求：保留知识结构蓝图中的具体课程知识点，增加至少 4 个一级分支，"
        "每个一级分支至少 2 个具体子节点，并补充易错辨析与实践应用节点。"
    )
    return {
        "mindmap_revision_notes": notes,
        "mindmap_outline": outline,
    }


@traced_node
async def mindmap_output(state: TutorState) -> dict:
    """Export final mindmap artifacts and emit the user-facing AI message."""
    tree = state.get("mindmap_tree") or {}
    if not tree:
        return {
            "error": "当前知识依据不足，未能生成可导出的思维导图。",
            "messages": [
                AIMessage(content="当前知识依据不足，暂时无法生成质量可靠的知识点思维导图。请补充课程主题、章节或材料后重试。")
            ],
        }

    review_verdict = state.get("mindmap_review_verdict", "")
    review_reason = state.get("mindmap_review_reason", "")
    title = str(tree.get("title") or "知识点思维导图")
    artifact = create_xmind_artifact(tree, title=title)
    payload = {
        "title": title,
        "tree": tree,
        "xmind_url": artifact["xmind_url"],
        "artifact_id": artifact["artifact_id"],
        "filename": artifact["filename"],
        "quality_warning": review_verdict == "reject",
        "review_reason": review_reason,
    }

    warning = ""
    if review_verdict == "reject":
        warning = f"质量提示：审查智能体认为仍存在风险（{review_reason}），已保留可下载草稿，建议补充课程材料后再生成。"

    content = (
        f"已生成《{title}》知识点思维导图。你可以在下方预览 Mermaid、Markdown/Markmap、交互树图，"
        f"并按需下载 .xmind、SVG 或 PNG。{warning}"
    )
    return {
        "mindmap_artifact": payload,
        "messages": [AIMessage(content=content)],
    }


def should_rewrite_mindmap(state: TutorState) -> str:
    """Route reviewer output to rewrite or final export."""
    if state.get("mindmap_review_verdict") != "reject":
        return "output"
    max_rounds = int(get_setting("mindmap.max_generation_rounds", 3) or 3)
    current_round = int(state.get("mindmap_round", 0) or 0)
    return "rewrite" if current_round < max_rounds else "output"
