"""Collaborative mindmap resource-generation nodes."""

from __future__ import annotations

import logging
import os
from typing import Any, Literal

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from src.config import get_setting, load_prompt
from src.graph.llm import invoke_plain_llm_fail_fast
from src.graph.state import LearningState
from src.llm.structured_output import (
    get_fallback_modes,
    get_llm_output_mode,
    get_max_raw_chars,
    invoke_structured_llm,
)
from src.observability.a3_trace import emit_a3_trace
from src.tools.mindmap_tool import create_xmind_artifact, normalize_mindmap_tree
from src.tracing import traced_llm_call, traced_node

logger = logging.getLogger(__name__)


class MindmapNode(BaseModel):
    """Unified JSON tree node used by all mindmap renderers."""

    title: str = Field(description="Short concrete node label")
    note: str | None = Field(default=None, description="Optional learning hint")
    children: list["MindmapNode"] = Field(default_factory=list)


class MindmapArtifact(BaseModel):
    """Structured JSON tree generated by mindmap_agent."""

    title: str
    tree: MindmapNode


class MindmapReviewVerdict(BaseModel):
    """Structured quality gate output for mindmap_reviewer."""

    verdict: Literal["approve", "reject"]
    reason: str


if hasattr(MindmapNode, "model_rebuild"):
    MindmapNode.model_rebuild()
else:
    MindmapNode.update_forward_refs()


def validate_mindmap_artifact(parsed: BaseModel) -> str:
    if not isinstance(parsed, MindmapArtifact):
        return "root expected MindmapArtifact"
    if not str(parsed.title or "").strip():
        return "title must be non-empty"
    if parsed.tree is None:
        return "tree must be present"
    if not str(parsed.tree.title or "").strip():
        return "tree.title must be non-empty"
    if not parsed.tree.children:
        return "tree.children must contain at least one child"
    return ""


def validate_review_verdict(parsed: BaseModel) -> str:
    if not isinstance(parsed, MindmapReviewVerdict):
        return "root expected MindmapReviewVerdict"
    if parsed.verdict not in {"approve", "reject"}:
        return "verdict must be approve or reject"
    if not str(parsed.reason or "").strip():
        return "reason must be non-empty"
    return ""


def _last_human_query(state: LearningState) -> str:
    for msg in reversed(state.get("messages", [])):
        if isinstance(msg, HumanMessage):
            return str(msg.content)
    return ""


def _model_to_dict(model: BaseModel) -> dict:
    if hasattr(model, "model_dump"):
        return model.model_dump()
    return model.dict()


def _format_keypoints(state: LearningState) -> str:
    keypoints = state.get("keypoints", [])
    return ", ".join(str(item) for item in keypoints if str(item).strip()) or "No explicit keypoints."


def _format_context(context: list[dict]) -> str:
    if not context:
        return "No judged evidence is available. Do not invent citations."
    parts: list[str] = []
    for idx, item in enumerate(context[:8], 1):
        source = item.get("source") or item.get("title") or item.get("url") or "learning material"
        content = str(item.get("content") or item.get("snippet") or item.get("text") or "")[:800]
        if content:
            parts.append(f"[{idx}] Source: {source}\n{content}")
    return "\n\n".join(parts) or "Judged evidence has no readable body."


def _render_prompt(prompt_name: str, replacements: dict[str, str]) -> str:
    prompt = load_prompt(prompt_name)
    for key, value in replacements.items():
        prompt = prompt.replace("{" + key + "}", value)
    return prompt


def _is_web_evidence(item: dict) -> bool:
    return (
        item.get("source_type") == "web"
        or item.get("type") in {"web_evidence", "web_supplement"}
        or item.get("legacy_type") == "web_supplement"
        or item.get("type_legacy") == "web_supplement"
    )


def _web_evidence_items(context: list[dict]) -> list[dict]:
    return [item for item in context if _is_web_evidence(item)]


def _tree_stats(tree: dict[str, Any]) -> tuple[int, int]:
    def visit(node: Any, depth: int) -> tuple[int, int]:
        if not isinstance(node, dict):
            return 0, depth - 1
        count = 1
        max_depth = depth
        for child in node.get("children") or []:
            child_count, child_depth = visit(child, depth + 1)
            count += child_count
            max_depth = max(max_depth, child_depth)
        return count, max_depth

    return visit(tree, 1)


def _local_review_failure(tree: dict[str, Any], _query: str) -> str:
    node_count, depth = _tree_stats(tree)
    if node_count < 6:
        return f"mindmap has too few nodes: {node_count}"
    if depth < 2:
        return f"mindmap is too shallow: {depth}"
    return ""


@traced_node
async def mindmap_planner(state: LearningState) -> dict:
    query = _last_human_query(state)
    context = state.get("context", [])
    web_evidence = _web_evidence_items(context)
    emit_a3_trace(
        logger,
        "mindmap_planner",
        {
            "context_count": len(context),
            "context_web_count": len(web_evidence),
            "dual_source_mode": bool(state.get("dual_source_mode")),
            "evidence_judge_state": state.get("evidence_judge_state", ""),
        },
        state=state,
        env_flag="LOG_GENERATION_SUMMARY",
    )
    prompt = _render_prompt(
        "mindmap_planner",
        {"question": query, "keypoints": _format_keypoints(state), "context": _format_context(context)},
    )
    outline = await invoke_plain_llm_fail_fast(
        node_name="mindmap_planner",
        llm_node="mindmap",
        messages=[
            SystemMessage(content="You are a university course knowledge-structure planner. Return a concrete mindmap outline only."),
            HumanMessage(content=prompt),
        ],
        state=state,
        temperature=get_setting("mindmap.temperature", 0.2),
    )
    if not outline.strip():
        raise ValueError("mindmap_planner produced empty outline")
    return {
        "mindmap_outline": outline,
        "mindmap_tree": {},
        "mindmap_artifact": {},
        "mindmap_review_verdict": "",
        "mindmap_review_reason": "",
        "mindmap_revision_notes": "",
        "mindmap_round": 0,
    }


@traced_node
async def mindmap_agent(state: LearningState) -> dict:
    query = _last_human_query(state)
    outline = state.get("mindmap_outline", "")
    if not outline.strip():
        raise ValueError("mindmap outline is empty")
    round_no = int(state.get("mindmap_round", 0) or 0) + 1
    prompt = _render_prompt(
        "mindmap_agent",
        {
            "question": query,
            "keypoints": _format_keypoints(state),
            "context": _format_context(state.get("context", [])),
            "mindmap_outline": outline,
            "revision_notes": state.get("mindmap_revision_notes", "") or "None",
        },
    )
    model_name = get_setting("llm.mindmap.model", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))
    with traced_llm_call(model_name=model_name, node_name="mindmap_agent", temperature=get_setting("mindmap.temperature", 0.2)):
        structured_result = await invoke_structured_llm(
            node_name="mindmap_agent",
            llm_node="mindmap",
            schema=MindmapArtifact,
            messages=[
                SystemMessage(content="You are a JSON tree generator. Return only JSON for MindmapArtifact."),
                HumanMessage(content=prompt),
            ],
            output_mode=get_llm_output_mode("mindmap_agent"),
            fallback_modes=get_fallback_modes("mindmap_agent"),
            business_validator=validate_mindmap_artifact,
            state=state,
            max_raw_chars=get_max_raw_chars("mindmap_agent"),
        )
    result = structured_result.parsed
    if not isinstance(result, MindmapArtifact):
        raise TypeError("mindmap_agent parsed result is not MindmapArtifact")
    title = result.title.strip() or "Knowledge mindmap"
    tree = normalize_mindmap_tree(_model_to_dict(result.tree))
    if not tree.get("title"):
        tree["title"] = title
    return {
        "mindmap_tree": tree,
        "mindmap_round": round_no,
        "mindmap_review_verdict": "",
        "mindmap_review_reason": "",
    }


@traced_node
async def mindmap_reviewer(state: LearningState) -> dict:
    tree = state.get("mindmap_tree") or {}
    if not tree:
        raise ValueError("mindmap tree is empty")
    local_failure = _local_review_failure(tree, _last_human_query(state))
    if local_failure:
        return {
            "mindmap_review_verdict": "reject",
            "mindmap_review_reason": local_failure,
            "mindmap_revision_notes": f"Please rewrite: {local_failure}",
        }
    prompt = _render_prompt(
        "mindmap_reviewer",
        {
            "question": _last_human_query(state),
            "mindmap_outline": state.get("mindmap_outline", ""),
            "mindmap_tree": str(tree),
        },
    )
    model_name = get_setting("llm.mindmap.model", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))
    with traced_llm_call(model_name=model_name, node_name="mindmap_reviewer", temperature=0.0):
        structured_result = await invoke_structured_llm(
            node_name="mindmap_reviewer",
            llm_node="mindmap",
            schema=MindmapReviewVerdict,
            messages=[
                SystemMessage(content="You are a course resource quality reviewer. Return only JSON."),
                HumanMessage(content=prompt),
            ],
            output_mode=get_llm_output_mode("mindmap_reviewer"),
            fallback_modes=get_fallback_modes("mindmap_reviewer"),
            business_validator=validate_review_verdict,
            state=state,
            max_raw_chars=get_max_raw_chars("mindmap_reviewer"),
        )
    result = structured_result.parsed
    if not isinstance(result, MindmapReviewVerdict):
        raise TypeError("mindmap_reviewer parsed result is not MindmapReviewVerdict")
    return {
        "mindmap_review_verdict": result.verdict,
        "mindmap_review_reason": result.reason.strip(),
        "mindmap_revision_notes": "" if result.verdict == "approve" else f"Please rewrite: {result.reason.strip()}",
    }


@traced_node
async def mindmap_rewrite(state: LearningState) -> dict:
    reason = state.get("mindmap_review_reason", "")
    if not reason.strip():
        raise ValueError("mindmap rewrite requested without review reason")
    return {
        "mindmap_revision_notes": f"Revise the mindmap according to reviewer feedback:\n{reason}",
        "mindmap_outline": state.get("mindmap_outline", ""),
    }


@traced_node
async def mindmap_output(state: LearningState) -> dict:
    tree = state.get("mindmap_tree") or {}
    if not tree:
        raise ValueError("mindmap tree is empty")
    title = str(tree.get("title") or "Knowledge mindmap")
    artifact = create_xmind_artifact(tree, title=title)
    payload = {
        "title": title,
        "tree": tree,
        "xmind_url": artifact["xmind_url"],
        "artifact_id": artifact["artifact_id"],
        "filename": artifact["filename"],
        "quality_warning": False,
        "review_reason": state.get("mindmap_review_reason", ""),
    }
    return {
        "mindmap_artifact": payload,
        "messages": [AIMessage(content=f"Generated mindmap: {title}")],
    }


def should_rewrite_mindmap(state: LearningState) -> str:
    if state.get("mindmap_review_verdict") != "reject":
        return "output"
    max_rounds = int(get_setting("mindmap.max_generation_rounds", 3) or 3)
    current_round = int(state.get("mindmap_round", 0) or 0)
    if current_round < max_rounds:
        return "rewrite"
    raise RuntimeError(f"mindmap rejected after max rounds: {state.get('mindmap_review_reason', '')}")
