"""Context Engineering Kernel public API."""

from src.context_engineering.budget import (
    build_context_budget,
    build_context_usage_payload,
    compute_context_usage,
    get_context_engineering_config,
    get_model_context_limit,
)
from src.context_engineering.compaction import (
    CompactBoundaryV1,
    CompactionResultV1,
    ConversationSummaryV2,
    FullCompactionDecisionV1,
    ProviderBoundUsageV1,
    build_compact_boundary,
    evaluate_full_compaction,
)
from src.context_engineering.packing import (
    ContextPackingError,
    PackedContext,
    PackingDecision,
    emit_context_packing_shadow,
    pack_context_items,
)
from src.context_engineering.model_view import (
    ModelViewBuildResult,
    ModelViewConfigV1,
    ModelViewProjectionV1,
    build_model_view_projection,
    get_model_view_config,
    model_view_projection_trace_payload,
)
from src.context_engineering.schema import (
    ContextBudget,
    ContextConfigError,
    ContextItem,
    ContextProviderError,
    ContextUsageError,
    ContextUsageReport,
    TokenCount,
)
from src.context_engineering.tokenizer import (
    count_messages_tokens,
    count_schema_chars,
    count_text_tokens,
    estimate_messages_tokens_mixed,
    estimate_text_tokens_mixed,
    message_content_to_text,
)
from src.context_engineering.trace import (
    build_context_items_collected_event,
    build_context_provider_error_event,
    build_context_usage_error_event,
    build_context_usage_event,
    emit_context_items_collected,
    emit_context_provider_error,
    emit_context_usage,
    emit_context_usage_error,
)

__all__ = [
    "ContextBudget",
    "ContextConfigError",
    "ContextItem",
    "ContextPackingError",
    "ContextProviderError",
    "ContextUsageError",
    "ContextUsageReport",
    "CompactBoundaryV1",
    "CompactionResultV1",
    "ConversationSummaryV2",
    "FullCompactionDecisionV1",
    "ModelViewBuildResult",
    "ModelViewConfigV1",
    "ModelViewProjectionV1",
    "PackedContext",
    "PackingDecision",
    "ProviderBoundUsageV1",
    "TokenCount",
    "build_context_items_collected_event",
    "build_context_provider_error_event",
    "build_context_budget",
    "build_context_usage_error_event",
    "build_context_usage_event",
    "build_context_usage_payload",
    "build_compact_boundary",
    "build_model_view_projection",
    "compute_context_usage",
    "count_messages_tokens",
    "count_schema_chars",
    "count_text_tokens",
    "emit_context_items_collected",
    "emit_context_packing_shadow",
    "emit_context_provider_error",
    "emit_context_usage",
    "emit_context_usage_error",
    "evaluate_full_compaction",
    "estimate_messages_tokens_mixed",
    "estimate_text_tokens_mixed",
    "get_context_engineering_config",
    "get_model_context_limit",
    "get_model_view_config",
    "model_view_projection_trace_payload",
    "message_content_to_text",
    "pack_context_items",
]
